import { baseBuiltins, REFERENCE_OPERATOR_MANIFEST } from "@nativr/base";
import { PROTOCOL_VERSION } from "@nativr/protocol";
import type { CapabilityManifest } from "@nativr/protocol";

/** Frozen capability manifest for the current documented language subset. */
export const CAPABILITIES = Object.freeze({
  nativrVersion: "0.1.1",
  protocolVersion: PROTOCOL_VERSION,
  languageSubsetVersion: "0.236.0",
  syntax: {
    literals: "supported",
    assignment: "supported",
    arithmetic: "supported",
    calls: "supported",
    functions: "supported",
    lexicalClosures: "supported",
    lazyArguments: "supported",
    argumentMatching: "supported",
    missingArguments: "supported",
    switchSelection: "supported",
    typeInspection: "supported",
    atomicCoercion: "supported",
    complexVectors: "supported",
    rawVectors: "supported",
    sequences: "supported",
    lists: "supported",
    names: "supported",
    comparisons: "supported",
    logicalOperators: "supported",
    randomNumbers: "supported",
    stringHelpers: "supported",
    dimensions: "supported",
    descriptiveStatistics: "supported",
    dataFrames: "supported",
    replacement: "supported",
    replacementFunctions: "supported",
    factors: "supported",
    applyFamily: "supported",
    datesTimes: "supported",
    sortingMatching: "supported",
    if: "supported",
    loops: "supported",
    return: "supported",
    subset: "supported",
    namespace: "supported",
    formula: "supported",
    pipe: "supported",
    s3ClassMetadata: "supported",
    s3MethodDispatch: "supported",
    s4: "supported",
    r6Construction: "supported",
    vctrsClassConstruction: "supported",
    ellipsis: "supported",
    quotedEvaluation: "supported",
    expressionVectors: "supported",
    callConstruction: "supported",
    substitution: "supported",
    firstClassOperators: "supported",
    matchedCalls: "supported",
    environments: "supported",
    pairlists: "supported",
    textParsing: "supported",
    dynamicEvaluation: "supported",
  },
  packages: ["base", "stats", "graphics", "grDevices", "utils", "methods"].map((packageName) => ({
    name: packageName,
    referenceVersion: "R 4.6.x documented behavior",
    functions: baseBuiltins
      .filter((definition) => definition.package === packageName)
      .map((definition) => ({
        name: definition.name,
        compatibility: definition.metadata.compatibilityLevel,
      })),
  })),
  backends: [...new Set(REFERENCE_OPERATOR_MANIFEST.map((operator) => operator.backend))],
} satisfies CapabilityManifest);
