export { EvaluationContext, DEFAULT_RUNTIME_LIMITS } from "./context.js";
export {
  createEnvironment,
  createForcedPromise,
  createMissingPromise,
  createPromise,
  forcePromise,
  lookupBinding,
  setBinding,
} from "./environment.js";
export {
  NativRError,
  REvaluationError,
  RParseError,
  RResourceLimitError,
  RRuntimeDisposedError,
  RTypeMismatchError,
  RUnsupportedFeatureError,
} from "./errors.js";
export type { NativRErrorOptions } from "./errors.js";
export { Evaluator } from "./evaluator.js";
export type {
  DetailedEvaluationResult,
  EvaluationResult,
  EvaluatorOptions,
  RuntimePackageDefinition,
  RuntimePackageDependency,
  RuntimePackageImport,
  RuntimePackageResource,
  RuntimePackageTextResource,
  RuntimeS3Method,
} from "./evaluator.js";
export { deparseAst } from "./language.js";
export { censusRuntimeMemory, estimateRObjectSize } from "./memory.js";
export {
  compressGzipBytes,
  decodeRBase64Resource,
  decompressDeflateRawBytes,
  decompressGzipBytes,
  decodeRSerialization,
  decodeRSerializationFile,
  decodeRWorkspaceFile,
  encodeRSerialization,
  encodeRSerializationFile,
} from "./serialization.js";
export type {
  RDecodedSerialization,
  RSerializationEnvironments,
  RSerializationMetadata,
  RSerializationWriteOptions,
  RWorkspaceEntry,
} from "./serialization.js";
export {
  characterBytesAt,
  characterBytesFromValue,
  characterEncodingAt,
  characterValueFromBytes,
  characterVector,
  complexVector,
  dataFrameRowCount,
  dataFrameValue,
  doubleVector,
  factorLevels,
  factorValue,
  integerVector,
  isAtomic,
  isDataFrame,
  isFactor,
  isMissing,
  isVector,
  listValue,
  logicalVector,
  missingValue,
  NATIVR_PACKAGE_LIBRARY_PATH,
  NATIVR_SYSTEM_LIBRARY_PATH,
  pairlistValue,
  rawVector,
  R_NULL,
  vectorClasses,
  vectorDimensions,
  vectorNames,
  withClasses,
  withAttribute,
  withDimensions,
  withNames,
  withoutAttribute,
  withoutClasses,
  functionDebugRegistry,
  FUNCTION_DEBUG_STATE_KEY,
  GLOBAL_CALLING_HANDLERS_STATE_KEY,
  OUTPUT_ROUTER_STATE_KEY,
  runtimeOutputRouter,
} from "./values.js";
export {
  extractListMember,
  extractVectorElement,
  replaceDimensions,
  replaceCoordinateMatrix,
  replaceListMember,
  replaceTwoDimensions,
  replaceVectorElement,
  replaceVectorSubset,
  subsetCoordinateMatrix,
  subsetDimensions,
  subsetTwoDimensions,
  subsetVector,
} from "./subset.js";
export type {
  BuiltinCallArgument,
  BuiltinDefinition,
  BuiltinInvocation,
  BuiltinKind,
  BuiltinMetadata,
  CancellationToken,
  OperatorContext,
  RAttributes,
  RBuiltin,
  RBinding,
  RCharacterEncoding,
  RCharacterVector,
  RComplexVector,
  RClosure,
  RDoubleVector,
  RDebuggableFunction,
  RDots,
  REnvironment,
  RExpression,
  RFormula,
  RFunctionDebugMetadata,
  RFunctionDebugRegistry,
  RGraphicsEvent,
  RGraphicsBoxplotGroup,
  RGraphicsLegendEntry,
  RGraphicsLegendPosition,
  RGraphicsPoint,
  RGraphicsText,
  RGraphicsPolygon,
  RGraphicsSegment,
  RIntegerVector,
  RList,
  RLogicalVector,
  RNull,
  ROutput,
  RSystemCommandRequest,
  RSystemCommandResult,
  RUrlRequest,
  RUrlResult,
  RPairlist,
  RPromise,
  RRawVector,
  RLanguage,
  RSymbol,
  RuntimeLimits,
  RuntimeOutputRouter,
  RuntimeMemoryAreaStatistics,
  RuntimeMemoryStatistics,
  RuntimeOperators,
  RValue,
  RVector,
  RVectorBase,
  RWarning,
} from "./values.js";
