export { EvaluationContext, DEFAULT_RUNTIME_LIMITS, RUNTIME_LIMIT_PROFILES } from "./context.js";
export type { RuntimeProfile } from "./context.js";
export { isCanonicalBase64 } from "./base64.js";
export {
  createEnvironment,
  createForcedPromise,
  createMissingPromise,
  createPromise,
  forcePromise,
  lookupBinding,
  removeBinding,
  setActiveBinding,
  setBinding,
  setParentEnvironment,
} from "./environment.js";
export {
  NativRError,
  RConditionError,
  REvaluationError,
  RParseError,
  RResourceLimitError,
  RRuntimeDisposedError,
  RTypeMismatchError,
  RUnsupportedFeatureError,
} from "./errors.js";
export type { NativRErrorOptions } from "./errors.js";
export { coreBuiltinPackageName, Evaluator } from "./evaluator.js";
export type {
  DetailedEvaluationResult,
  EvaluationResult,
  EvaluatorOptions,
  RuntimePackageDefinition,
  RuntimePackageDependency,
  RuntimePackageImport,
  RuntimePackageResource,
  RuntimePackageTextResource,
  RuntimeBuiltinBinding,
  RuntimeStaticPackageDefinition,
  RuntimeS3Method,
} from "./evaluator.js";
export {
  deparseAst,
  deparseSourceAst,
  deparseSourceLinesAst,
  languageEntries,
  languageFromEntries,
  languageValueAst,
  quoteLanguageAst,
} from "./language.js";
export { censusRuntimeMemory, estimateRObjectSize } from "./memory.js";
export { normalizePosixCharacterClasses } from "./regex.js";
export {
  compressGzipBytes,
  decodeRBase64Resource,
  decompressDeflateRawBytes,
  decompressGzipBytes,
  decodeRSerialization,
  decodeRSerializationFile,
  decodeRWorkspaceFile,
  encodeRSerialization,
  encodeRSerializationFile,
} from "./serialization.js";
export type {
  RDecodedSerialization,
  RSerializationEnvironments,
  RSerializationMetadata,
  RSerializationWriteOptions,
  RWorkspaceEntry,
} from "./serialization.js";
export {
  characterBytesAt,
  characterBytesFromValue,
  characterEncodingAt,
  characterValueFromBytes,
  characterVector,
  complexVector,
  dataFrameRowCount,
  dataFrameValue,
  doubleVector,
  factorLevels,
  factorValue,
  integerVector,
  isAtomic,
  isDataFrame,
  isFactor,
  isMissing,
  isVector,
  listValue,
  logicalVector,
  missingValue,
  NATIVR_PACKAGE_LIBRARY_PATH,
  NATIVR_PACKAGE_SOURCE_RESOURCE_ROOT,
  NATIVR_SYSTEM_LIBRARY_PATH,
  PACKAGE_SOURCE_EVALUATION_DIRECTORY_STATE_KEY,
  SOURCE_REFERENCE_CONTEXT_STATE_KEY,
  S4_SLOT_REPLACEMENT_VALIDATOR_STATE_KEY,
  objectAttributes,
  objectClasses,
  pairlistValue,
  rawVector,
  rVersionValue,
  R_NULL,
  vectorClasses,
  vectorDimensions,
  vectorNames,
  withClasses,
  withAttribute,
  withDimensions,
  withNames,
  withoutAttribute,
  withoutClasses,
  functionDebugRegistry,
  FUNCTION_DEBUG_STATE_KEY,
  CONDITION_HANDLER_SEQUENCE_STATE_KEY,
  DYNAMIC_CALLING_HANDLERS_STATE_KEY,
  EXITING_HANDLER_STACK_STATE_KEY,
  ExitingHandlerJump,
  GLOBAL_CALLING_HANDLERS_STATE_KEY,
  OUTPUT_ROUTER_STATE_KEY,
  RESTART_FRAME_COUNTER_STATE_KEY,
  RESTART_STACK_STATE_KEY,
  RestartJump,
  runtimeOutputRouter,
} from "./values.js";
export {
  extractListMember,
  extractVectorElement,
  replaceDimensions,
  replaceCoordinateMatrix,
  replaceExpressionElement,
  replaceExpressionSubset,
  replaceListMember,
  replaceTwoDimensions,
  replaceVectorElement,
  replaceVectorSubset,
  subsetCoordinateMatrix,
  subsetDimensions,
  subsetTwoDimensions,
  subsetVector,
} from "./subset.js";
export type {
  BuiltinCallArgument,
  BuiltinDefinition,
  BuiltinInvocation,
  BuiltinKind,
  BuiltinMetadata,
  CancellationToken,
  OperatorContext,
  RAttributes,
  RActiveBinding,
  RBuiltin,
  RBinding,
  RCharacterEncoding,
  RCharacterVector,
  RComplexVector,
  RClosure,
  RDoubleVector,
  RDebuggableFunction,
  RDots,
  REnvironment,
  RExpression,
  RExternalPointer,
  RFormula,
  RFunctionDebugMetadata,
  RFunctionDebugRegistry,
  RGraphicsEvent,
  RGraphicsBoxplotGroup,
  RGraphicsLegendEntry,
  RGraphicsLegendPosition,
  RGraphicsPoint,
  RGraphicsText,
  RGraphicsPolygon,
  RGraphicsSegment,
  RIntegerVector,
  RList,
  RLogicalVector,
  RNull,
  RNativeCallRequest,
  RNativeModuleDefinition,
  RNativeRoutineDefinition,
  ROutput,
  RSystemCommandRequest,
  RSystemCommandRedirection,
  RSystemCommandResult,
  RSocketRequest,
  RSocketResult,
  RUrlRequest,
  RUrlResult,
  RPairlist,
  RPromise,
  RRawVector,
  RLanguage,
  RSymbol,
  RuntimeLimits,
  RuntimeOutputRouter,
  RuntimeMemoryAreaStatistics,
  RuntimeMemoryStatistics,
  RuntimeOperators,
  ExitingConditionHandlerFrame,
  RestartFrame,
  RValue,
  RVector,
  RVectorBase,
  RWarning,
  S4SlotReplacementValidator,
} from "./values.js";
