export { EvaluationContext, DEFAULT_RUNTIME_LIMITS } from "./context.js";
export {
  createEnvironment,
  createForcedPromise,
  createMissingPromise,
  createPromise,
  forcePromise,
  lookupBinding,
  setBinding,
} from "./environment.js";
export {
  NativRError,
  REvaluationError,
  RParseError,
  RResourceLimitError,
  RRuntimeDisposedError,
  RTypeMismatchError,
  RUnsupportedFeatureError,
} from "./errors.js";
export type { NativRErrorOptions } from "./errors.js";
export { Evaluator } from "./evaluator.js";
export type {
  DetailedEvaluationResult,
  EvaluationResult,
  EvaluatorOptions,
  RuntimePackageDefinition,
  RuntimePackageDependency,
  RuntimePackageImport,
  RuntimePackageResource,
  RuntimeS3Method,
} from "./evaluator.js";
export { deparseAst } from "./language.js";
export {
  characterVector,
  complexVector,
  dataFrameRowCount,
  dataFrameValue,
  doubleVector,
  factorLevels,
  factorValue,
  integerVector,
  isAtomic,
  isDataFrame,
  isFactor,
  isMissing,
  isVector,
  listValue,
  logicalVector,
  missingValue,
  pairlistValue,
  rawVector,
  R_NULL,
  vectorClasses,
  vectorDimensions,
  vectorNames,
  withClasses,
  withAttribute,
  withDimensions,
  withNames,
  withoutAttribute,
  withoutClasses,
  GLOBAL_CALLING_HANDLERS_STATE_KEY,
} from "./values.js";
export {
  extractListMember,
  extractVectorElement,
  replaceDimensions,
  replaceCoordinateMatrix,
  replaceListMember,
  replaceTwoDimensions,
  replaceVectorElement,
  replaceVectorSubset,
  subsetCoordinateMatrix,
  subsetDimensions,
  subsetTwoDimensions,
  subsetVector,
} from "./subset.js";
export type {
  BuiltinCallArgument,
  BuiltinDefinition,
  BuiltinInvocation,
  BuiltinKind,
  BuiltinMetadata,
  CancellationToken,
  OperatorContext,
  RAttributes,
  RBuiltin,
  RBinding,
  RCharacterVector,
  RComplexVector,
  RClosure,
  RDoubleVector,
  RDots,
  REnvironment,
  RExpression,
  RFormula,
  RGraphicsEvent,
  RGraphicsBoxplotGroup,
  RGraphicsLegendEntry,
  RGraphicsLegendPosition,
  RGraphicsPoint,
  RGraphicsText,
  RGraphicsPolygon,
  RGraphicsSegment,
  RIntegerVector,
  RList,
  RLogicalVector,
  RNull,
  ROutput,
  RPairlist,
  RPromise,
  RRawVector,
  RLanguage,
  RSymbol,
  RuntimeLimits,
  RuntimeOperators,
  RValue,
  RVector,
  RVectorBase,
  RWarning,
} from "./values.js";
