import { createHash } from "node:crypto";
import { copyFile, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const root = path.resolve(fileURLToPath(new URL("..", import.meta.url)));
const sourceRoot = requiredDirectory("NATIVR_LBFGSB_SOURCE");
const f2c = requiredExecutable("F2C");
const f2cInclude = requiredDirectory("F2C_INCLUDE");
const emcc = requiredExecutable("EMCC");
const expectedSourceSha256 = "137d03b5d704491b5002c0207565fd4dcf3089ef61f593279520cab8b0db3ccd";
const expectedF2cSha256 = "e4233301ed2d9c550558a37609636a3a2922aea642ad2915a660f9ac640046fc";
const expectedF2cHeaderSha256 = "3a5bcb7c693224ca5dc35714350874dee733c32a20aae10b031ffce06088c555";
const output = path.join(root, "packages", "nativr", "src", "lbfgsb-bytes.ts");
const buildRoot = await mkdtemp(path.join(os.tmpdir(), "nativr-lbfgsb-"));

try {
  const fortranSource = path.join(sourceRoot, "routines.f");
  await verifyHash([fortranSource, path.join(sourceRoot, "License.txt")], expectedSourceSha256);
  await verifyHash([f2c], expectedF2cSha256);
  await verifyHash([path.join(f2cInclude, "f2c.h")], expectedF2cHeaderSha256);
  const localFortran = path.join(buildRoot, "routines.f");
  await copyFile(fortranSource, localFortran);
  run(f2c, ["-A", "-R", path.basename(localFortran)], buildRoot);

  const wrapper = path.join(buildRoot, "lbfgsb.mjs");
  run(
    emcc,
    [
      path.join(buildRoot, "routines.c"),
      path.join(root, "scripts", "lbfgsb-support.c"),
      `-I${f2cInclude}`,
      "-O2",
      "--no-entry",
      "-sMODULARIZE=1",
      "-sEXPORT_ES6=1",
      "-sENVIRONMENT=web,worker,node",
      "-sFILESYSTEM=0",
      "-sALLOW_MEMORY_GROWTH=1",
      "-sINITIAL_HEAP=1048576",
      "-sEXPORTED_FUNCTIONS=_setulb_,_malloc,_free",
      "-o",
      wrapper,
    ],
    buildRoot,
  );
  const wasm = await readFile(path.join(buildRoot, "lbfgsb.wasm"));
  const module = new WebAssembly.Module(wasm);
  const imports = WebAssembly.Module.imports(module);
  if (
    imports.length !== 1 ||
    imports[0]?.module !== "env" ||
    imports[0]?.name !== "emscripten_resize_heap" ||
    imports[0]?.kind !== "function"
  ) {
    throw new Error(`Unexpected L-BFGS-B Wasm imports: ${JSON.stringify(imports)}.`);
  }
  const hash = createHash("sha256").update(wasm).digest("hex");
  await writeFile(
    output,
    `// Generated by scripts/build-lbfgsb.mjs from the official BSD-3-Clause L-BFGS-B 2.1.\n` +
      `// Source snapshot SHA-256: ${expectedSourceSha256}\n` +
      `// Wasm SHA-256: ${hash}\n` +
      `export const LBFGSB_WASM_SHA256 = ${JSON.stringify(hash)};\n` +
      `export const LBFGSB_WASM_BASE64 = ${JSON.stringify(wasm.toString("base64"))};\n`,
    "utf8",
  );
  console.log(`Built ${path.relative(root, output)} (${wasm.length} Wasm bytes, SHA-256 ${hash}).`);
} finally {
  await rm(buildRoot, { recursive: true, force: true });
}

async function verifyHash(files, expected) {
  const hash = createHash("sha256");
  for (const file of files) hash.update(await readFile(file));
  const actual = hash.digest("hex");
  if (actual !== expected)
    throw new Error(`Unexpected source/tool hash ${actual}; expected ${expected}.`);
}

function run(command, args, cwd) {
  const result = spawnSync(command, args, { cwd, encoding: "utf8", stdio: "pipe" });
  if (result.status !== 0) {
    throw new Error(
      `${command} failed (${result.status ?? "no status"}):\n${result.stdout}\n${result.stderr}`,
    );
  }
}

function requiredDirectory(name) {
  const value = process.env[name];
  if (value === undefined || value.length === 0) throw new Error(`${name} must name a directory.`);
  return path.resolve(value);
}

function requiredExecutable(name) {
  const value = process.env[name];
  if (value === undefined || value.length === 0)
    throw new Error(`${name} must name an executable.`);
  return path.resolve(value);
}
